site_name: Regovar
theme: readthedocs
markdown_extensions:
 - extra
 - nl2br
 - sane_lists
 - abbr
 - attr_list
 - def_list
 - tables 
docs_dir: rtd


nav:
 - 'ACCUEIL': 'index.md'
 - 'INSTALLATION':
    - 'Avec Docker (Test/Dev)': 'installation/docker.md'
    - 'Avec Saltstack (Production)': 'installation/saltstack.md'
    - 'Configuration': 'installation/configuration.md'
    - 'Maintenance': 'installation/maintenance.md'
 - 'UTILISATION': 
    - 'Présentation': 'usage/presentation.md'
    - 'Concepts de base': 'usage/concepts.md'
    - 'Analyse - Filtrage': 'usage/filtering.md'
    - 'Analyse - Pipeline': 'usage/pipeline.md'
    - 'FAQ': 'usage/faq.md'
 - 'TUTORIELS':
    - 'Filtrage': 'tutorials/filtering.md'
    - 'Pipeline': 'tutorials/pipeline.md'
    - 'Autres': 'tutorials/global.md'
- 'LE PROJET':
    - 'Organisation': 'project/organisation.md'
    - 'Historique': 'project/history.md'
- 'SPECIFICATIONS':
    - 'Besoins': 'specs/uses_cases.md'
    - 'Spécification fonctionnelles': 'specs/functionals.md'
    - 'Architecture': 'specs/architecture.md'
    - 'Définition des interfaces': 'specs/interfaces.md'
    - 'Modèle de données': 'specs/database.md'
    - 'Spécification techniques': 'specs/technicals.md'
    - 'Tests et validation': 'specs/tests.md'
    - 'Etudes': 'specs/discussions.md'
 - 'DEVELOPPEUR':
    - 'Environnement de travail': 'developer/environment.md'
    - 'Bonnes pratiques': 'developer/good_practices.md'
    - 'Intégration continue': 'developer/continuous_build.md'
    - 'Tests': 'developer/tests.md'
    - 'Qualité du code': 'developer/code_quality.md'
    - 'Tickets github': 'developer/github_issue.md'
    - 'Branches & Pullrequest': 'developer/github_pullrequest.md'
 - 'DEVELOPPEMENT':
    - 'API REST': 'development/rest.md'
    - 'API CLI': 'development/cli.md'
    - 'Pirus': 'development/pirus.md'
    - 'Authentification': 'development/authentication.md'
    - 'Gestion des erreurs': 'development/errors.md'
    - 'Gestion des logs': 'development/logs.md'
 
